
author:
    - name: Sage Ginther
      email: ginthersg@vcu.edu

date: 04/19/2025

format:
    html:
        theme: cosmo
        toc: true
        embed-resources: true
        code-copy: true

execute:
  echo: true
  eval: true
  cache: false
